language: python
python:
  - "2.7"
dist: trusty
sudo: required
services:
  - docker
install:
  - docker build -t shibataka000/ansible_playbooks_test .
script:
  - docker run -it --privileged shibataka000/ansible_playbooks_test
notifications:
  email: false
