language: python
python:
  - "2.7"
dist: trusty
sudo: required
services:
  - docker
install:
  - docker build -t shibataka000/run_playbooks .
script:
  - docker run -it --privileged shibataka000/run_playbooks
notifications:
  email: false
