- hosts: all
  become: yes
  roles:
    - docker
    - docker_compose
    - docker_machine
    - terraform
    - openjdk8
    - sbt
    - pyenv
    - pyenv_virtualenv
    - golang
    - assert_all_roles_installed
