- hosts: all
  become: yes
  roles:
    # Docker
    - docker
    - docker_compose
    - docker_machine
    # Terraform
    - terraform
    # Java8
    - openjdk8
    # Scala
    - sbt
    # Go
    - golang
