- hosts: all
  become: yes
  vars:
    - repo: Ladicle/kubectl-bindrole
    - binary_name: kubectl-bindrole
    - asset_id: kubectl-bindrole_linux-amd64.tar.gz
    - release_id: latest
    - path_in_archive: kubectl-bindrole
  tasks:
    - name: "Install release binary"
      include: "install-archived-release-binary.yml"
