- hosts: all
  become: yes
  vars:
    - repo: wercker/stern
    - binary_name: stern
    - asset_id: stern_linux_amd64
    - release_id: latest
  tasks:
    - name: "Install release binary"
      include: "install-release-binary.yml"
    - name: "Make sure installed"
      shell: "stern --version"
