# Input variables
# - download_url
# - binary_name
# - path_in_archive
- name: "Download archived release binary"
  get_url:
    url: "{{ download_url }}"
    dest: /tmp
    force: yes
  register: download
- name: "Unarchive archived release binary"
  unarchive:
    src: "{{ download.dest }}"
    dest: /tmp
    remote_src: yes
    list_files: yes
  register: unarchived_contents
- name: "Copy release binary"
  copy:
    src: /tmp/{{ unarchived_contents.files[0] }}{{ path_in_archive }}
    dest: /usr/local/bin/{{ binary_name }}
    mode: 0775
    force: yes
