version: 2.1
jobs:
  playbook:
    docker:
      - image: ubuntu:22.04
    environment:
      - GOPATH: /root/go
    parameters:
      playbook:
        type: string
        default: ""
    steps:
      - checkout
      - run:
          name: Install ansible
          command: |
            apt-get update
            apt-get install python3-pip -y
            pip3 install ansible
      - run:
          name: Install ansible playbook
          command: |
            ansible-playbook -i hosts playbooks/<< parameters.playbook >>.yml
workflows:
  build:
    jobs:
      - playbook:
          name: docker
          playbook: docker
      - playbook:
          name: golang
          playbook: golang
      - playbook:
          name: python
          playbook: python
      - playbook:
          name: powershell
          playbook: powershell
      - playbook:
          name: azurecli
          playbook: azurecli
      - playbook:
          name: dotnet
          playbook: dotnet
      - playbook:
          name: awscli
          playbook: awscli
      - playbook:
          name: telepresence
          playbook: telepresence
  nightly:
    jobs:
      - playbook:
          name: docker
          playbook: docker
      - playbook:
          name: golang
          playbook: golang
      - playbook:
          name: python
          playbook: python
      - playbook:
          name: powershell
          playbook: powershell
      - playbook:
          name: azurecli
          playbook: azurecli
      - playbook:
          name: dotnet
          playbook: dotnet
      - playbook:
          name: awscli
          playbook: awscli
      - playbook:
          name: telepresence
          playbook: telepresence
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
