version: 2.1
jobs:
  playbook:
    docker:
      - image: ubuntu
    parameters:
      playbook:
        type: string
        default: ""
    steps:
      - checkout
      - run:
          name: Install ansible
          command: |
            apt-get update
            apt-get install python-pip -y
            pip install ansible
      - run:
          name: Install ansible playbook
          command: |
            ansible-playbook -i hosts playbooks/<< parameters.playbook >>.yml
workflows:
  build:
    jobs:
      - playbook:
          name: docker
          playbook: docker
      - playbook:
          name: docker-compose
          playbook: golang-release/docker-compose
      - playbook:
          name: docker-machine
          playbook: golang-release/docker-machine
      - playbook:
          name: terraform
          playbook: terraform
      - playbook:
          name: golang
          playbook: golang
      - playbook:
          name: sam
          playbook: sam
      - playbook:
          name: python
          playbook: python
      - playbook:
          name: powershell
          playbook: powershell
      - playbook:
          name: azurecli
          playbook: azurecli
      - playbook:
          name: dotnetcore
          playbook: dotnetcore
      - playbook:
          name: kubectx
          playbook: kubectx
  nightly:
    jobs:
      - playbook:
          name: docker
          playbook: docker
      - playbook:
          name: docker-compose
          playbook: golang-release/docker-compose
      - playbook:
          name: docker-machine
          playbook: golang-release/docker-machine
      - playbook:
          name: terraform
          playbook: terraform
      - playbook:
          name: golang
          playbook: golang
      - playbook:
          name: sam
          playbook: sam
      - playbook:
          name: python
          playbook: python
      - playbook:
          name: powershell
          playbook: powershell
      - playbook:
          name: azurecli
          playbook: azurecli
      - playbook:
          name: dotnetcore
          playbook: dotnetcore
      - playbook:
          name: kubectx
          playbook: kubectx
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
