---
- name: "Add repository"
  apt_repository:
    repo: "deb https://dl.bintray.com/sbt/debian /"
- name: "Add apt key"
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 2EE0EA64E40A89B84B2DF73499E82A75642AC823
- name: "Install sbt"
  apt:
    name: sbt
    update_cache: yes
