---
- name: "Install unzip"
  apt:
    name: unzip
- name: "Download latest release info from GitHub"
  get_url:
    url: https://api.github.com/repos/hashicorp/terraform/releases/latest
    dest: /tmp/terraform.json
    force: yes
- name: "Get latest release info"
  shell: "cat /tmp/terraform.json"
  register: releases
- name: "Get latest version"
  set_fact:
    version: "{{ (releases.stdout | from_json).tag_name | regex_replace('v', '')}}"
- name: "Download terraform"
  get_url:
    url: https://releases.hashicorp.com/terraform/{{ version }}/terraform_{{ version }}_linux_amd64.zip
    dest: /tmp/terraform.zip
    force: yes
- name: "Unarchive terraform"
  unarchive:
    src: /tmp/terraform.zip
    dest: /usr/local/bin
    remote_src: yes
