- hosts: all
  become: yes
  vars:
    - repo: Ladicle/kubectl-bindrole
    - binary_name: kubectl-bindrole
    - asset_id: kubectl-bindrole_linux-amd64.tar.gz
    - release_id: latest
    - path_in_archive: kubectl-bindrole
  tasks:
    - name: "Get GitHub release tag name"
      include: "../tasks/get-github-release-tag-name.yml"
    - name: "Set download url"
      set_fact:
        download_url: https://github.com/{{ repo }}/releases/download/{{ tag_name }}/{{ asset_id }}
    - name: "Install release binary"
      include: "../tasks/install-archived-release-binary.yml"
    - name: "Make sure installed"
      shell: "kubectl bindrole --version"
