- hosts: all
  become: yes
  vars:
    - repo: kubernetes-sigs/kustomize
    - binary_name: kustomize
    - asset_id: kustomize_v3.3.0_linux_amd64.tar.gz
    - release_id: tags/kustomize/v3.3.0
    - path_in_archive: ""
  tasks:
    - name: "Get GitHub release tag name"
      include: "../tasks/get-github-release-tag-name.yml"
    - name: "Set download url"
      set_fact:
        download_url: https://github.com/{{ repo }}/releases/download/{{ tag_name }}/{{ asset_id }}
    - name: "Install release binary"
      include: "../tasks/install-archived-release-binary.yml"
    - name: "Make sure installed"
      shell: "kustomize version"
