- hosts: all
  become: yes
  tasks:
    - name: "Install unzip"
      apt:
        name: unzip
    - name: "Download awscli.zip"
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip
        force: yes
    - name: "Unarchive awscli.zip"
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: yes
    - name: "Check whether awscliv2 is already installed or not"
      stat:
        path: /usr/local/aws-cli/v2/current
      register: sym
    - name: "Install awscliv2"
      shell: "sh /tmp/aws/install"
      when: sym.stat.islnk is not defined
    - name: "Update awscliv2"
      shell: "sh /tmp/aws/install --update"
      when: sym.stat.islnk is defined
    - name: "Make sure installed"
      shell: "aws --version"
