- hosts: all
  become: yes
  tasks:
    - name: "Install lsb-release"
      apt:
        name: lsb-release
        update_cache: yes
    - name: "Add GPG key"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
    - name: "Get \"lsb_release -cs\""
      shell: "lsb_release -cs"
      register: lsb_release
    - name: "Add repository"
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable edge"
    - name: "Install docker"
      apt:
        name: docker-ce
        update_cache: yes
    # Comment in following tasks when you run this playbook.
    # - name: "Start docker daemon"
    #   service:
    #     name: docker
    #     state: started
    # - name: "Make sure installed"
    #   shell: "docker version"
