- hosts: all
  become: yes
  tasks:
    - name: "Download latest release info from GitHub"
      get_url:
        url: https://api.github.com/repos/docker/compose/releases/latest
        dest: /tmp/docker_compose.json
        force: yes
    - name: "Get latest release info"
      shell: "cat /tmp/docker_compose.json"
      register: releases
    - name: "Get latest version"
      set_fact:
        version: "{{ (releases.stdout | from_json).tag_name }}"
    - name: "Download docker-compose"
      get_url:
        url: https://github.com/docker/compose/releases/download/{{ version }}/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 0775
        force: yes
    - name: "Make sure installed"
      shell: "docker-compose version"
