- hosts: all
  become: yes
  tasks:
    - name: "Install lsb-release"
      apt:
        name: lsb-release
        update_cache: yes
    - name: "Get \"lsb_release -rs\""
      shell: "lsb_release -rs"
      register: lsb_release
    - name: "Register Microsoft key and feed"
      apt:
        deb: https://packages.microsoft.com/config/ubuntu/{{ lsb_release.stdout }}/packages-microsoft-prod.deb
    - name: "Install apt-transport-https"
      apt:
        name: apt-transport-https
        update_cache: yes
    - name: "Install .NET SDK"
      apt:
        name: dotnet-sdk-2.1
        update_cache: yes
