- hosts: all
  become: yes
  tasks:
    - name: "Install .NET 6 SDK"
      apt:
        name: dotnet-sdk-{{ version }}
        update_cache: yes
    - name: "Make sure installed"
      shell: "dotnet --version"
