- hosts: all
  become: yes
  vars:
    go_version: 1.10.3
  tasks:
    - name: "Download golang"
      get_url:
        url: https://storage.googleapis.com/golang/go{{ go_version }}.linux-amd64.tar.gz
        dest: /tmp/golang.tar.gz
        force: yes
    - name: "Unarchive golang"
      unarchive:
        src: /tmp/golang.tar.gz
        dest: /usr/local
        remote_src: yes
    - name: "Make sure installed"
      shell: "/usr/local/go/bin/go version"
