- hosts: all
  become: yes
  vars_prompt:
    - name: repo
      prompt: "Enter repository name"
      private: no
      default: wercker/stern
    - name: asset_id
      prompt: "Enter asset name"
      private: no
      default: stern_linux_amd64
    - name: release_id
      prompt: "Enter release name"
      private: no
      default: latest
  tasks:
    - name: "Get binary name"
      set_fact:
        binary_name: "{{ repo.split('/')[1] }}"
    - name: "Download release info"
      get_url:
        url: https://api.github.com/repos/{{ repo }}/releases/{{ release_id }}
        dest: "/tmp/{{ binary_name }}.json"
        force: yes
    - name: "Get release info"
      shell: "cat /tmp/{{ binary_name }}.json"
      register: releases
    - name: "Get version"
      set_fact:
        version: "{{ (releases.stdout | from_json).tag_name }}"
    - name: "Install release binary"
      get_url:
        url: https://github.com/{{ repo }}/releases/download/{{ version }}/{{ asset_id }}
        dest: /usr/local/bin/{{ binary_name }}
        mode: 0775
        force: yes
