- hosts: all
  become: yes
  vars:
    version: latest
  tasks:
    - name: "Get latest golang version"
      uri:
        url: https://go.dev/VERSION?m=text
        return_content: yes
      register: latest_version
      when: version == "latest"
    - name: "Determine install version when version == \"latest\""
      set_fact:
        install_version: "{{ latest_version.content }}"
      when: version == "latest"
    - name: "Determine install version when version != \"latest\""
      set_fact:
        install_version: "go{{ version }}"
      when: version != "latest"
    - name: "Get stats of /usr/local/go"
      stat:
        path: /usr/local/go
      register: go
    - name: "Remove /usr/local/go"
      file:
        state: absent
        path: /usr/local/go
      when: go.stat.exists
    - name: "Download golang"
      get_url:
        url: https://go.dev/dl/{{ install_version }}.linux-amd64.tar.gz
        dest: /tmp/golang.tar.gz
        force: yes
    - name: "Unarchive golang"
      unarchive:
        src: /tmp/golang.tar.gz
        dest: /usr/local
        remote_src: yes
    - name: "Make sure installed"
      shell: "/usr/local/go/bin/go version"
