- hosts: all
  become: yes
  vars:
    - repo: helm/helm
    - release_id: tags/v3.0.0-beta.5
    - path_in_archive: /helm
    - binary_name: helm
  tasks:
    - name: "Get GitHub release tag name"
      include: "../tasks/get-github-release-tag-name.yml"
    - name: "Set download url"
      set_fact:
        download_url: https://get.helm.sh/helm-{{ tag_name }}-linux-amd64.tar.gz
    - name: "Install archived release binary"
      include: "../tasks/install-archived-release-binary.yml"
    - name: "Make sure installed"
      shell: "helm version"
