- hosts: all
  become: yes
  tasks:
    - name: "Install lsb-release"
      apt:
        name: lsb-release
        update_cache: yes
    - name: "Add apt key"
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
    - name: "Get \"lsb_release -cs\""
      shell: "lsb_release -cs"
      register: lsb_release_c
    - name: "Get \"lsb_release -rs\""
      shell: "lsb_release -rs"
      register: lsb_release_r
    - name: "Add repository"
      apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/{{ lsb_release_r.stdout }}/prod {{ lsb_release_c.stdout }} main"
    - name: "Install powershell"
      apt:
        name: powershell
        update_cache: yes
    - name: "Make sure installed"
      shell: "pwsh --version"
