- hosts: all
  become: yes
  vars:
    python_version: 3.8.2
  tasks:
    - name: "Install gcc"
      apt:
        name: gcc
        update_cache: yes
    - name: "Install make"
      apt:
        name: make
        update_cache: yes
    - name: "Install libssl-dev"
      apt:
        name: libssl-dev
        update_cache: yes
    - name: "Install libreadline-dev"
      apt:
        name: libreadline-dev
        update_cache: yes
    - name: "Install zlib1g-dev"
      apt:
        name: zlib1g-dev
        update_cache: yes
    - name: "Download Python-{{ python_version }}.tar.xz"
      get_url:
        url: https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tar.xz
        dest: /tmp/Python-{{ python_version }}.tar.xz
        force: yes
    - name: "Unarchive Python-{{ python_version }}.tar.xz"
      unarchive:
        src: /tmp/Python-{{ python_version }}.tar.xz
        dest: /usr/local/src/
        remote_src: yes
    - name: "./configure"
      shell: ./configure
      args:
        chdir: /usr/local/src/Python-{{ python_version }}
    - name: "make"
      make:
        chdir: /usr/local/src/Python-{{ python_version }}
    - name: "make install"
      make:
        chdir: /usr/local/src/Python-{{ python_version }}
        target: install
    - name: "Make sure installed"
      shell: "python3 --version"
