- hosts: all
  become: yes
  vars:
    - repo: hashicorp/terraform
    - release_id: latest
    - path_in_archive: ""
    - binary_name: terraform
  tasks:
    - name: "Install unzip"
      apt:
        name: unzip
    - name: "Get GitHub release tag name"
      include: "../tasks/get-github-release-tag-name.yml"
    - name: "Get terraform version"
      set_fact:
        version: "{{ tag_name | regex_replace('v', '')}}"
    - name: "Set download url"
      set_fact:
        download_url: https://releases.hashicorp.com/terraform/{{ version }}/terraform_{{ version }}_linux_amd64.zip
    - name: "Install archived release binary"
      include: "../tasks/install-archived-release-binary.yml"
    - name: "Make sure installed"
      shell: "terraform version"
